User.create!(name: 'Arya')
User.create!(name: 'Snow')
User.create!(name: 'Sansa')
User.create!(name: 'Brandon')
User.create!(name: 'Ned')
User.create!(name: 'Khaleesi')

Category.create!(name: 'Opening', priority: 1)
Category.create!(name: 'Middle-game', priority: 2)
Category.create!(name: 'End-game', priority: 3)
Category.create!(name: 'Tactics', priority: 4)
Category.create!(name: 'Strategy', priority: 5)
